""" 
    This program tests if UDP packets are being recieved from local host
    Generated by Claude Code
"""

import socket, struct

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(("127.0.0.1", 5005))
print("Listening on :5005 — move the board...")

while True:
    data, _ = sock.recvfrom(12)
    x, y, seq = struct.unpack("ffI", data)
    print(f"seq={seq:05d}  x={x:+.2f}  y={y:+.2f}")