/*
 * Richy Manzo
 * 2026-04-27
 * This cpp file implements the ImageExporter class
 * which exports the smoothed strokes as 28x28 image for neural network input.
 */

 #include "imageExporter.h"
 #include <fstream>
 #include <cmath>

 void ImageExporter::render(vector<vector<Point>> smoothedStrokes, int canvasWidth, int canvasHeight) {
    
    // To clear the grid before rendering a new image.
    clear();

    // Loop through each stroke
    for (int i = 0; i < smoothedStroked.size(); i++) {

        // Get the current stroke
        vector<Point> stroke = smoothedStrokes[i];

        // Skip strokes with less than 2 points, as they cannot form a line.
        if (stroke.size() < 2) {
            continue;
        }

        // Loop through consecutive points in the stroke to draw lines between them.
        for (int j = 0; j < stroke.size() - 1; j++) {

            // Scale first x and y coordinates to fit in 28x28 grid.
            float x0 = ((float)stroke[j].x / canvasWidth) * 28;
            float y0 = ((float)stroke[j].y / canvasHeight) * 28;
            
            // Scale second x and y coordinates to fit in 28x28 grid.
            float x1 = ((float)stroke[j + 1].x / canvasWidth) * 28;
            float y1 = ((float)stroke[j + 1].y / canvasHeight) * 28;

            // Draw a line between the two points.
            drawLine(x0, y0, x1, y1);
        }
    }
 }

// This function was generated by Claude Code
// drawLine() fills in grid cells between two points using linear interpolation.
// We figure out how many steps to take based on the distance between the points,
// then move a little bit each step and light up the cell we land on.
void ImageExporter::drawLine(float x0, float y0, float x1, float y1) {

    // calculate the distance between the two points
    float dx = x1 - x0;
    float dy = y1 - y0;

    // steps = how many cells we need to fill between the two points
    // we use the larger of dx and dy so we don't skip any cells
    int steps = (int)(abs(dx) > abs(dy) ? abs(dx) : abs(dy));

    // if the two points are the same cell, just light it up and return
    if (steps == 0) {
        int gx = (int)x0;
        int gy = (int)y0;
        if (gx >= 0 && gx < 28 && gy >= 0 && gy < 28) {
            grid[gy][gx] = 255;
        }
        return;
    }

    // xStep and yStep are how much we move each iteration
    float xStep = dx / steps;
    float yStep = dy / steps;

    // walk from start to end one step at a time
    for (int s = 0; s <= steps; s++) {
        // current position along the line
        int gx = (int)(x0 + xStep * s);
        int gy = (int)(y0 + yStep * s);

        // make sure we are within the 28x28 grid before writing
        if (gx >= 0 && gx < 28 && gy >= 0 && gy < 28) {
            grid[gy][gx] = 255;  // white pixel
        }
    }
}

// This function saves the rendered image as a PGM file
bool ImageExporter::save(string filename) {

    // ofstream opens a file for writing
    ofstream file(filename);

    // Writes the header to the file
    file << "P2\n"; // P2 means it's a plain text PGM file
    file << "28 28\n"; // width and height
    file << "255\n"; // max pixel value

    // Write each pixel row by row
    for (int row = 0; row < 28; row++) {
        for (int col = 0; col < 28; col++) {
            file << grid[row][col];
            if (col < 27) {
                file << " "; // Space between pixel values, but not after the last one in the row
            }
        }
        file << "\n"; // Newline at the end of each row
    }

    file.close();
    return true; // Return true to indicate the file was saved successfully
}

// clear() resets the 28x28 grid to all zeros (black)
void ImageExporter::clear() {
    for (int row = 0; row < 28; row++) {
        for (int col = 0; col < 28; col++) {
            grid[row][col] = 0; // Set each cell to 0 (black)
        }
    }
}